repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: go-unit-tests
        name: go unit tests
        entry: go test -p=1 ./... -v
        language: system
        pass_filenames: false
        types: [go]
