module.exports = {
  apps: [
    {
      name: "hiyab-backend",
      script: "./backend/bin/hiyab-api",
      cwd: "./backend",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env_file: "./backend/.env",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/backend-error.log",
      out_file: "./logs/backend-out.log",
      log_file: "./logs/backend-combined.log",
      time: true,
      merge_logs: true,
      // Restart delay
      min_uptime: "10s",
      max_restarts: 10,
      restart_delay: 4000,
    },
    {
      name: "hiyab-frontend",
      script: "npx",
      args: "serve -s dist -l 4000",
      cwd: "./frontend",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/frontend-error.log",
      out_file: "./logs/frontend-out.log",
      log_file: "./logs/frontend-combined.log",
      time: true,
      merge_logs: true,
    },
    {
      name: "hiyab-dashboard",
      script: "npx",
      args: "serve -s dist -l 3000",
      cwd: "./dashboard",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/dashboard-error.log",
      out_file: "./logs/dashboard-out.log",
      log_file: "./logs/dashboard-combined.log",
      time: true,
      merge_logs: true,
    },
  ],
};
