package domain

import "errors"

var (
	ErrNotFound            = errors.New("resource not found")
	ErrInvalidInput        = errors.New("invalid input")
	ErrUnauthorized        = errors.New("unauthorized")
	ErrInternalServer      = errors.New("internal server error")
	ErrCreateFailed        = errors.New("failed to create resource")
	ErrUpdateFailed        = errors.New("failed to update resource")
	ErrDeleteFailed        = errors.New("failed to delete resource")
	ErrSearchFailed        = errors.New("failed to search resources")
	ErrDatabase            = errors.New("database error")
	ErrInvalidCredentials  = errors.New("invalid credentials")
	ErrUserNotFound        = errors.New("user not found")
	ErrUserAlreadyExists   = errors.New("user already exists")
	ErrTokenExpired        = errors.New("token expired")
	ErrTokenInvalid        = errors.New("token invalid")
	ErrInvalidTokenType    = errors.New("invalid token type")
	ErrTokenNotFound       = errors.New("token not found")
	ErrPermissionDenied    = errors.New("permission denied")
	ErrDatabaseError       = errors.New("database error")
	ErrResourceNotFound    = errors.New("resource not found")
	ErrResourceNotAllowed  = errors.New("resource not allowed")
	ErrUserInactive        = errors.New("user is inactive")
	ErrCommissionNotFound  = errors.New("commission not found")
	ErrInvalidAmount       = errors.New("invalid amount")
	ErrHouseNotFound       = errors.New("house not found")
	ErrTransactionNotFound = errors.New("transaction not found")
	ErrGameNotFound        = errors.New("game not found")
	ErrInvalidDateRange    = errors.New("invalid date range")
	ErrInvalidSortOrder    = errors.New("invalid sort order")
)
